name: ci
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) 先に pnpm を用意
      - uses: pnpm/action-setup@v4
        with:
          version: 9.12.0
          run_install: false

      # 2) その後に Node + pnpm キャッシュ
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          # monorepo の場合:
          # cache-dependency-path: "**/pnpm-lock.yaml"

      - run: pnpm --version

      - run: pnpm i --frozen-lockfile
      - run: pnpm lint
      - run: pnpm typecheck
      - run: pnpm format:check